### ISSUE TITLE
Не перепутаны Psi и psi?

### ISSUE THREAD

**Issue by BigBigGamer** [FedorSarafanov/quantum_mechanics#2]
Тут \Psi и \psi - так и должно быть, не напутано? ну еще \dot кривой надо {} а не ()
https://github.com/FedorSarafanov/quantum_mechanics/blob/8cb6b45dbb880cd5615958ac148b78ecf247d017/lect/perturbation_theory.tex#L832-L835

**Comment by FedorSarafanov** [comment]
Перепутаны, исправлены
